language: node_js
node_js:
  - "8"

before_script:
  - npm run build

script:
  - npm test

after_success:
  - npm run coverage

deploy:
  provider: surge
  project: ./
  domain: betweenjs.surge.sh
  on:
    all_branches: true
